### ISSUE TITLE
`prefer-power-assert` does not allow the use of `t.true()`

### ISSUE THREAD

**Issue by bdougherty** [avajs/eslint-plugin-ava#117]
Since `t.true` works with power-assert, the rule should not warn when using it. I think it should also allow `t.false` and `t.falsy` as well.

In the gitter chat, @sindresorhus [suggested](https://gitter.im/avajs/ava?at=574e861f6bbc2d1d4df00e6a) that `prefer-power-assert` should enforce `t.true` over `t.truthy`, but that seems to me like that is covered by the `use-true-false` rule.

Happy to submit a PR with the changes.

**Comment by jamestalmage** [comment]
> but that seems to me like that is covered by the use-true-false rule

Just add `true` and `false` to the list of accepted assertions in the `prefer-power-assert` rule.

---

PR Welcome
