### ISSUE TITLE
Upgrade to ESLint 3

### ISSUE THREAD

**Issue by sindresorhus** [avajs/eslint-plugin-ava#128]
New rule format: http://eslint.org/blog/2016/07/eslint-new-rule-format (We should use the automatic translation)

And bump the peerDependencies and devDependencies.

**Comment by novemberborn** [comment]
Since ESLint drops Node.js 0.10 and 0.12 support, should this plugin do the same? Can we somehow be compatible with both ESLint versions?

**Comment by sindresorhus** [comment]
I already did in https://github.com/avajs/eslint-plugin-ava/commit/f6919aac96728e63794d95d0f8479bbfb7a5c191. Probably not, and even if we could, it's time to move on.

**Comment by jfmengels** [comment]
> Can we somehow be compatible with both ESLint versions?

Looks like ESLint already supported both styles, so that makes the migration easier, and could potentially allow us to support Node 0.1X. That said, I agree that we should move on.
