### ISSUE TITLE
`no-async-fn-without-await` rule

### ISSUE THREAD

**Issue by sindresorhus** [avajs/eslint-plugin-ava#132]
I've seen many tests where `async` functions are used without any `await` keyword. I'm pretty sure there's no reason to use `async` functions if you don't use `await` in it, right?

Example: https://github.com/sindresorhus/shell-env/pull/3/files/929775e4fbc79991d3fdfea40e6141ac4c64f211..fce68229a89e0d00fa1b703b752a2b9f70114375

Open to suggestions for a better rule name.

**Comment by jfmengels** [comment]
:+1:
The name is fine IMO

**Comment by jfmengels** [comment]
Actually... does it make sense to have this in this plugin?
I don't see the point in any code to have an async function without await.

Does anyone know if there's a difference between `async function() {}` and `function() {}` actually (when the body is empty)? Does the async one always return a Promise maybe?

**Comment by novemberborn** [comment]
> Does the async one always return a Promise maybe?

Pretty sure it does, yes. You could use it with `throw` so that you always get a rejected promise.

That said, I don't see how that makes sense for AVA tests.

**Comment by sindresorhus** [comment]
> I think it might be a better fit for XO.

Thought about that, but code using an async function probably expects a Promise. In AVA it doesn't matter as we can handle both. So I don't see how it could be made generic.

> Does the async one always return a Promise maybe?

Yes

**Comment by jfmengels** [comment]
> Thought about that, but code using an async function probably expects a Promise.

```js
async function foo() {
  return 2;
}

foo().then(...);
```

Do you mean that this should be allowed in source code (== non-test code)? If so, then I agree that this should probably better be here than in `eslint-plugin-xo`.

I'm not sure I like having this implicitness versus the explicit `return Promise.resolve(2);`, but that's a whole different stylistic issue, that I haven't played enough with yet.

**Comment by sindresorhus** [comment]
Yes, I'm only concerned about the "test implementation" function here.

> I'm not sure I like having this implicitness versus the explicit return Promise.resolve(2);, but that's a whole different stylistic issue, that I haven't played enough with yet.

Easy cases like that could be handled, but it quickly get's hard to statically analyze. I think we should handle the "test implementation" thing here and continue discussion about a more comprehensive implementation in the XO plugin.
