### ISSUE TITLE
Forbid importing / requiring test files

### ISSUE THREAD

**Issue by jfmengels** [avajs/eslint-plugin-ava#141]
Using the same regex logic that we use in https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-ignored-test-files.md, forbid importing a test file.

There is no good reason to import a test file. If you do, you are probably:
- re-using a helper function or test macro from a different test, which should be moved in a separate helper file
- Importing a test file from a source file, which you shouldn't mix
- Naming a source file as something that will be considered by AVA as a test file

**Comment by sindresorhus** [comment]
👍
