### ISSUE TITLE
Update recommended config to include new rules

### ISSUE THREAD

**Issue by jfmengels** [avajs/eslint-plugin-ava#144]
Since activating rules in the recommended config is a breaking change, this should be done only when releasing major versions. In the meantime, new rules are added but turned off 

To turn on:
- [ ] no-async-fn-without-await
- [ ] no-duplicate-modifiers

**Comment by novemberborn** [comment]
> Since activating rules in the recommended config is a breaking change, this should be done only when releasing major versions.

Why not release a major version though?

**Comment by jfmengels** [comment]
We could, but I don't feel like adding a new major version every month is the way to go.
With v3, we had the excuse of dropping support for Node versions, which was a breaking change, but from now on, we probably won't have this kind of opportunity for a long time.

So yes, releasing major versions is possible and completely up to us, but I feel that the benefit of releasing a major version (= just adding recommended rules) outweighs the benefit of smooth upgrading. Upgrading to a major version is something that users will probably need to do manually and take the time for, even if it ends up being really short and simple.

I prefer waiting for either a breaking change in our rules or external dependency, or just waiting for some time and quite a few rules to pile up.

It's totally a gut choice, let me know if you think we should do major versions more often.

**Comment by novemberborn** [comment]
> Upgrading to a major version is something that users will probably need to do manually and take the time for, even if it ends up being really short and simple.

Adding the new recommended-but-not-quite rules to their ESLint config takes more time than bumping the version.

**Comment by jfmengels** [comment]
You're right.

Another thing to take into account are bug fixes. The last version (3.1.0) shipped with 2 new rules and a bug fix, which they'll get for free in most cases through the magic of npm and semver. Had we shipped v4 instead, then users with v3 would have to upgrade to v4 to get it.

**Comment by novemberborn** [comment]
Sure, but most packages only receive bugfixes in the latest version. That's nothing new.
