### ISSUE TITLE
Create and maintain CHANGELOG.md

### ISSUE THREAD

**Issue by gajus** [avajs/eslint-plugin-ava#172]
It is impossible to keep up to speed with Ava changes without a changelog.

**Comment by vadimdemedes** [comment]
We describe all the changes in AVA with blog post-like releases in the AVA's repository, you can easily follow the changes there.

**Comment by gajus** [comment]
Information about changes should be present in the repository where the code is contained.

**Comment by vadimdemedes** [comment]
Wait, are you talking about AVA (as you mentioned in first post) or eslint plugin?

**Comment by gajus** [comment]
Sorry, eslint-plugin-ava.

**Comment by sindresorhus** [comment]
Changelog here: https://github.com/avajs/eslint-plugin-ava/commits/master

**Comment by gajus** [comment]
You are not following semantic versioning... :-(

Consider using https://github.com/semantic-release/semantic-release instead of inventing release tags.

**Comment by sindresorhus** [comment]
> You are not following semantic versioning... :-(

Yes, we are. What makes you think we are not?

> instead of inventing release tags.

What does this even mean?

**Comment by gajus** [comment]
> Yes, we are. What makes you think we are not?

https://github.com/avajs/eslint-plugin-ava/compare/v4.0.0...v4.2.0

You have not added any new features but the minor version was incremented twice.

> What does this even mean?

Using tags that do not represent changes:

* patch = bug fix
* minor = new feature
* major = any backwards incompatible change

See semver.org

**Comment by gajus** [comment]
Using `semantic-release` is really not hard, it saves *a lot of time* making releases and it established commit guidelines that result in easy to scan commit history, e.g. https://github.com/gajus/surgeon/commits/master

**Comment by sindresorhus** [comment]
> You have not added any new features but the minor version was incremented twice.

That's not correct:

- Enhancement: https://github.com/avajs/eslint-plugin-ava/commit/c65eaa76fa07231d7156d6a2e666b3cf403cd733
- Enhancement: https://github.com/avajs/eslint-plugin-ava/commit/37ef35b96e3de0b48143a151b687387b70dd795f

Neither of those were bug fixes and should be minor bump.

**Comment by gajus** [comment]
Fixing an expected behaviour is not a feature.

**Comment by gajus** [comment]
* c65eaa76fa07231d7156d6a2e666b3cf403cd733 Thats an addition, my mistake.
* 37ef35b96e3de0b48143a151b687387b70dd795f Says bug fix (of https://github.com/avajs/eslint-plugin-ava/issues/168).

Anyway, my point remains that as it is, tracking changes is extremely hard. Of 12 ESLint plugins that https://github.com/gajus/eslint-config-canonical extends, Ava is the only that does not implement a changelog.

**Comment by sindresorhus** [comment]
> Ava is the only that does not implement a changelog.

No:

- https://github.com/gajus/eslint-plugin-jsdoc/releases (This is yours...)
- https://github.com/dustinspecker/eslint-plugin-no-use-extend-native
- https://github.com/xjamundx/eslint-plugin-promise/blob/master/CHANGELOG.md (This is just a list of commits, so doesn't count)

**Comment by gajus** [comment]
> https://github.com/gajus/eslint-plugin-jsdoc/releases (This is yours...)

Fixed in https://github.com/gajus/eslint-plugin-jsdoc/commit/8f41c173cf96fc5e9f09ea5f54e2e63c2850aae0. Its really that simple.

You are maintaining a lot more libraries than I do, therefore I am in no position to give an authoritative suggestion. However, from my personal experience, using semantic-release takes a day to get used to, but it is a win-win for the authors and consumers. Author are able to make regular releases at a click of a button (in case of a PR) or by simply pushing changes upstream. Consumers are able to scan releases for changes that strictly adhere to feat/ breaking change/ fix convention.
