### ISSUE TITLE
Work with AVA 1.0

### ISSUE THREAD

**Issue by novemberborn** [avajs/eslint-plugin-ava#209]
I tried upgrading to the AVA 1.0 beta, but it looks like duplicate test titles are being generated. It'd be great if somebody could try the upgrade and figure out what's going on 😄

**Comment by sindresorhus** [comment]
Already reported: https://github.com/jfmengels/eslint-ava-rule-tester/issues/7

**Comment by novemberborn** [comment]
@sindresorhus oh nice!
