### ISSUE TITLE
no-ignored-test-files rule gives false alerts in monorepo setups

### ISSUE THREAD

**Issue by revelt** [avajs/eslint-plugin-ava#212]
Hi all,

Currently, if the setup is a monorepo, packages are located two levels deeper than normal, for example in `packages/<name>/`. This throws off rule `ava/no-ignored-test-files`:

![monorepo_subdirectories](https://user-images.githubusercontent.com/8344688/51018845-f3a97400-1570-11e9-882c-7d6837bece1c.png)

We should make the algorithm smarter and make it detect test is in `**/test/**/*.js` as opposed to strict `test/**/*.js`.

We already check `**/*.test.js`, it just does not cover the folder case mentioned above.

**Proposal**: turn `test/**/*.js` into `**/test/**/*.js`

Also, what to do if test.js is in monorepo package's root — we also might need `**/test.js`.

**Comment by StarpTech** [comment]
Hello, I have the same issue. Everything is marked with `ava/no-ignored-test-files`.

**Comment by revelt** [comment]
update: since 10 months ago I ended up not using this rule, here's one of my package's `.eslintrc` for your reference: https://gitlab.com/codsen/codsen/blob/master/packages/all-named-html-entities/.eslintrc.json

**Comment by novemberborn** [comment]
I think this should work with the latest versions of this plugin and AVA — the plugin should find the closest `package.json` from the file being linted, resolve the config from there, and then use it in these rules.

I'd appreciate a reproduction when this is not the case.

**Comment by revelt** [comment]
I tried but can't recreate the issue, somebody please confirm it's still happening. I'm happy to close. CC @StarpTech

**Comment by StarpTech** [comment]
I can still reproduce it.

I have a base config `ava.config.js` and two different for int and unit tests. In the base config, I didn't specify the test files. How is it possible to specifiy a different ava config?

I don't use a specific test directory. My test files are next to the source file.

```
foo.js
foo.spec.int.js
```

ava.config.js
```js
export default {
  cache: true,
  failFast: true,
  failWithoutAssertions: false,
  tap: true,
  verbose: true,
  compileEnhancements: false,
  babel: false,
  timeout: '10s',
  environmentVariables: {
    NODE_ICU_DATA: '../../node_modules/full-icu'
  },
  sources: ['server/**/*']
};
```

ava.int.config.js
```js
import baseConfig from './ava.config';

export default {
  ...baseConfig,
  files: ['**/*.spec.int.js']
};

```

**Comment by StarpTech** [comment]
I could solve my issue and it seems that it wasn't related to this one. Thanks for help.

**Comment by revelt** [comment]
Thanks all! Closing
