### ISSUE TITLE
Support new file and helper selection

### ISSUE THREAD

**Issue by novemberborn** [avajs/eslint-plugin-ava#238]
https://github.com/avajs/ava/pull/2103 changes how test files and helpers are selected. This impacts our `no-ignored-test-files` and `no-import-test-files` rules.

I suggest we add an `eslint-helper` file to the main `ava` package. It should take care of reading the config (accepting a project directory argument). The rules should then be able to call a function to determine whether something is a test or helper file.

There may be other places where we try to resolve AVA config. We should move those to `ava/eslint-helper` as well.

**Comment by sindresorhus** [comment]
@novemberborn Was this fixed by https://github.com/avajs/eslint-plugin-ava/commit/df6374ae05b8267ccdd8b2a15990c4be7892915a?

**Comment by novemberborn** [comment]
Yes, well spotted.
