### ISSUE TITLE
Add general rule tests

### ISSUE THREAD

**Issue by sindresorhus** [avajs/eslint-plugin-ava#242]
Like: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/package.js Can probably just borrow those directly.

**Comment by gurungrahul2** [comment]
@sindresorhus  can you help me for proceeding with this ? A little more pointer will work.

**Comment by gurungrahul2** [comment]
@sindresorhus `assertion-message` is deprecated but why the rule is still there? We need to add back the docs and tests to make the tests pass. Another problem i faced is `no-ignored-test-files` is rule which have two tests in different files like `no-ignored-test-files-with-package` and `no-ignored-test-files-without-package`, I should merge them ?

**Comment by sindresorhus** [comment]
> assertion-message is deprecated but why the rule is still there?

Graceful removal. We can remove it now though.

> Another problem i faced is no-ignored-test-files is rule which have two tests in different files like no-ignored-test-files-with-package and no-ignored-test-files-without-package, I should merge them ?

I would just add a manual ignore check for those.

**Comment by sindresorhus** [comment]
> Graceful removal. We can remove it now though.

Removed
