### ISSUE TITLE
Make `use-t-well` more auto-fixable

### ISSUE THREAD

**Issue by GMartigny** [avajs/eslint-plugin-ava#244]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/eslint-plugin-ava/issues/244)

When https://github.com/avajs/eslint-plugin-ava/pull/229 is merged, `use-t-well` will be able to autofix `falsey` to `falsy` (a common misspell).

This can be expanded further by creating a small list of common misspells that can be autofixed (`t.contxt`, `t.truthey`, `t.deepequal` ...)
I don't know what's the limit to the size of that list. It could even be allowed to customize it with an option.

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos). And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#277 Assertion methods auto correction for use-t-well rule, makes most misspells fixable](https://issuehunt.io/r/avajs/eslint-plugin-ava/pull/277)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/eslint-plugin-ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Sounds good. I don't think we need to make it customizable though.

**Comment by GMartigny** [comment]
If not customizable, we need to define a list of replacements that the plugin will care for.

Updated list here for convenience (not validated):
 - contxt => context
 - `/deepequal/i` => deepEqual
 - `/notdeepEqual/i` => notDeepEqual
 - throw => throws
 - notThrow => notThrows
 - `/notthrows/i` => notThrows
 - throwAsync => throwsAsync
 - `/throwsasync/i` => throwsAsync
 - notThrowAsync => notThrowsAsync
 - `/notthrowsasync/i` => notThrowsAsync
 - `/notregex/i` => notRegex

Any suggestion ?

**Comment by sindresorhus** [comment]
Your list looks good. I can't think of anything else.

**Comment by GMartigny** [comment]
I've just add regexp => regex for no [particular reasons](https://github.com/avajs/eslint-plugin-ava/pull/247#discussion_r287562765) 🙄

**Comment by stroncium** [comment]
@sindresorhus this inspired me to check my basic skills and I wrote simplistic auto correction module. It is able to fix all the mentioned corrections and some more. Should I add it?
