### ISSUE TITLE
`no-ignored-test-files` does not work when test files are manually transpiled

### ISSUE THREAD

**Issue by ehmicky** [avajs/eslint-plugin-ava#252]
If I understood correctly, the new `no-ignored-test-files` uses the Ava configuration to figure out where test files are. 

However I transpile my tests with Babel from `test/**` to `build/test/**`. I explicitly use `{ babel: false, compileEnhancements: false }`. 

Which means `test/**` are linted, but `build/test/**` are run by Ava. Under those circumstances, `no-ignored-test-files` assumption is wrong and reports all my test files with `error  AVA ignores this file`.

**Comment by novemberborn** [comment]
Yea you're right. I'm not sure what the best solution is. I guess we should add back a configuration option, allowing you to override the glob patterns. We'd have to change the [caching here](https://github.com/avajs/ava/blob/e1572d9f66fecfaf4ceb2a84814181b02c8d142e/eslint-plugin-helper.js#L10) to include a cache key that can be provided from the ESLint rule. That way we can derive a different helper for each use case.

How would you prefer to override the patterns? Override `files` and / or `helpers` statically, or perhaps run some code that receives the original values?

**Comment by ehmicky** [comment]
> How would you prefer to override the patterns? Override files and / or helpers statically, or perhaps run some code that receives the original values?

I'm not sure I understand the two approaches you mention, could you please rephrase them?

A array of globbing strings would work for my case, and probably other users with similar setups.
