### ISSUE TITLE
ava/no-import-test-files triggers for scoped packages

### ISSUE THREAD

**Issue by freaktechnik** [avajs/eslint-plugin-ava#253]
Using the recommended config of the plugin, `import Octokit from '@octokit/rest';` inside a file called `_stubs.js`, so an ava helper file, triggers the rule `ava/no-import-test-files` with the message "Test files should not be imported" for the whole line.

Example: https://travis-ci.org/mozillach/gh-projects-content-queue/jobs/540192593#L477

**Comment by GMartigny** [comment]
You file `_stubs.js` is considered a test file because it's under the `test` directory. The best thing you can do is to put all [non-test files related to test](https://github.com/avajs/ava/tree/master/test/helper) under a `helper` directory.
Alternatively, you can change your [AVA settings on helper files](https://github.com/avajs/ava/blob/master/docs/06-configuration.md).

**Comment by freaktechnik** [comment]
That is not what the rule error is saying though. It's saying I'm importing a test file, which is not what's happening.

**Comment by freaktechnik** [comment]
From a quick glance at the rule, I'd suspect this is because `@octokit/rest` does not match https://github.com/avajs/eslint-plugin-ava/blob/master/rules/no-import-test-files.js#L5, since @ is not in `\w`.

**Comment by GMartigny** [comment]
`@` not matching makes it considered as an internal module, but it should not be considered a test file anyway.

**Comment by freaktechnik** [comment]
Well, given how the helper seems to work it will just assume that there is a folder called `@octokit`, and a file called `rest` would be a test.

**Comment by novemberborn** [comment]
> `@` not matching makes it considered as an internal module, but it should not be considered a test file anyway.

Unfortunately we resolve the path relative to the file being linted, and when that's done with a scoped package we end up with a relative path inside the `test` directory: `test/@octokit/rest`.

I'll PR up a fix soon.

**Comment by novemberborn** [comment]
This should be fixed by #255.
