### ISSUE TITLE
Detect more assertions in the `t-prefer-regex` rule

### ISSUE THREAD

**Issue by sindresorhus** [avajs/eslint-plugin-ava#275]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/eslint-plugin-ava/issues/275)

See https://github.com/avajs/eslint-plugin-ava/issues/158#issuecomment-523830714

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos). And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#297 Add equality checks to `prefer-t-regex` rule](https://issuehunt.io/r/avajs/eslint-plugin-ava/pull/297)
- [#319 Detect more assertions in `prefer-t-regex`](https://issuehunt.io/r/avajs/eslint-plugin-ava/pull/319)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/eslint-plugin-ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JaniM** [comment]
Opened a PR.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see https://github.com/avajs/eslint-plugin-ava/pull/297 for previous attempt and its feedback.
