### ISSUE TITLE
Rule `use-test` conflicting with typing of `t.context`

### ISSUE THREAD

**Issue by pvdlg** [avajs/eslint-plugin-ava#293]
The [AVA documentation](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md#typing-tcontext) recommends to to type `t.context` as follow:
```js
import anyTest, {TestInterface} from 'ava';

const test = anyTest as TestInterface<{foo: string}>;
```

However importing AVA as `anyTest` instead of `test` triggers the `use-test` rule.

I can make a PR but I don't know what the best solution is. Any suggestion?

**Comment by sindresorhus** [comment]
Could we check if it's a TypeScript file and allow `anyTest` as a name then? I think the rule context exposes the source file name.

**Comment by novemberborn** [comment]
Heh, I've been using `ava` as the default import. But `anyTest` is still fine.

**Comment by novemberborn** [comment]
Thanks @pvdlg, 10.1.0 is now available 🎊
