### ISSUE TITLE
Rule proposal: enforce using (or not using) descriptions with assertions

### ISSUE THREAD

**Issue by ehmicky** [avajs/eslint-plugin-ava#299]
Assertions can optionally specify a description:

```js
t.is(value, true, 'description')
```

It would be nice to add a rule to enforce that either:
  - all assertions have a description, for the developers that think that those provide with better error messages
  - no assertions have a description, for the developers that think those are not useful

**Comment by sindresorhus** [comment]
This is already possible: https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/assertion-arguments.md#options

**Comment by ehmicky** [comment]
Oh I did look at the list of rules, but somehow I missed this. Great! Thanks a lot for pointing it out.
