### ISSUE TITLE
Remove redundant rule "no-async-fn-without-await"

### ISSUE THREAD

**Issue by KinectTheUnknown** [avajs/eslint-plugin-ava#308]
Understandably, the "ava/no-async-fn-without-await" rule was probably created before EsLint's ["require-await"](https://eslint.org/docs/rules/require-await) rule. Looking back at the [commit](https://github.com/avajs/eslint-plugin-ava/blob/a443d7a9c94165f42749938e6b491a7c10749b6c/package.json#L86) when this rule was originally added, the minimum EsLint version was 3.0.0 and according to EsLint's docs, "require-await" was added in 3.11.0.
However, the minimum requirement for EsLint is now 6.2.0, which means that all projects using this plugin should have the rule built-in to EsLint. Therefore, this rule should be deprecated in eslint-ava-plugin and removed in the next major version.

**Comment by sindresorhus** [comment]
It's not redundant. Some people (me included) might not want to use `require-await` as that rule [has a lot of false-positives](https://github.com/xojs/eslint-config-xo/commit/bbe8cd0a97296e9521770186126a47867e005f62). This rule, however, doesn't suffer from such false-positives.
