### ISSUE TITLE
`no-identical-title` crash

### ISSUE THREAD

**Issue by fisker** [avajs/eslint-plugin-ava#328]
This code `test.errors.some(error => error.suggestions)`, real world case 

- CI Log https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1306/checks?check_run_id=2637013180#step:5:8
- Code https://github.com/bmish/eslint-plugin-unicorn/blob/cdccaa7b67fbf138e7c4417610abb8124812efaf/test/utils/test.mjs#L19

**Comment by fisker** [comment]
Duplicate of #317?

**Comment by novemberborn** [comment]
> Duplicate of #317?

I can't tell (not familiar with how Unicorn tests are written), but… sure, let's say it's a duplicate?
