### ISSUE TITLE
Deprecate the `assertion-message` rule

### ISSUE THREAD

**Issue by sindresorhus** [avajs/eslint-plugin-ava#98]
It's now moot with the introduction of the [`assertion-arguments`](https://github.com/sindresorhus/eslint-plugin-ava/blob/master/docs/rules/assertion-arguments.md) rule.

What's the best-practise for deprecating rules with ESLint?

**Comment by ChristianMurphy** [comment]
https://github.com/eslint/eslint/issues/5845

**Comment by sindresorhus** [comment]
Just saw this: https://github.com/eslint/eslint/commit/49d3c1b20ee50bc661bb4c5ee74e0bc1bf2663d9, but ESLint doesn't actually use it nor pass it on to the formatter. I suggest we set this property and prefix `(DEPRECATED) ` to the rule messages. We should document this process.

Can be done for the next major version.
